### ISSUE TITLE
Request to update aar please

### ISSUE THREAD

**Issue by montecillodavidacn** [neurospeech/xamarin-shortcut-badger#5]
Hi  seen the source is adding vivo

https://github.com/leolin310148/ShortcutBadger/blob/9775db27771faadbc0317ea78428467eaf4a850e/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L58

Please update aar please.

**Comment by yauhenipakala** [comment]
Maybe this version of the library will help you (latest from original):

https://github.com/wcoder/ShortcutBadger

**Comment by ackava** [comment]
Updated to latest version
